# Generated by Django 6.0.7 on 2026-07-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='exchange',
            field=models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE'), ('NASDAQ', 'NASDAQ'), ('NYSE', 'NYSE')], default='NSE', max_length=20),
        ),
    ]
