# Generated by Django 6.0.7 on 2026-07-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='data_source',
            field=models.CharField(default='manual', max_length=20),
        ),
    ]
