# Generated by Django 6.0.7 on 2026-07-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='yahoo_symbol',
            field=models.CharField(blank=True, help_text='Yahoo Finance ticker (e.g. AAPL, RELIANCE.NS)', max_length=30, null=True),
        ),
    ]
